### ISSUE TITLE
No timeout on async-tcp stream wrapper

### ISSUE THREAD

**Issue by joelwurtz** [concurrent-php/ext-async#101]
It seems that using stream_set_timeout on an async-tcp stream has no effect.

I add support for this extension in https://github.com/php-http/socket-client/pull/42 and got a test that ensure we got timeout error as exception. It set a 1ms timeout and normally we got an error on connection (connection timed out from php) or an error when reading the stream (this is checked by reading meta data and checking that timed_out key is equals to true). Neither of those 2 errors are thrown when using the async extension.

I think i can check timeout by using the async API, but IMO existing behavior should be kept (having a php error on timeout)

**Comment by martinschroeder** [comment]
I introduced support for connect and read timeouts in my latest PR. I tested it against the linked branch in `php-http` and it enforces the timeout, the test still fails because the timeout exception is not a network exception as expected by the test case.

**Comment by joelwurtz** [comment]
Will test it as soon as i can

**Comment by joelwurtz** [comment]
Works fine :+1: thanks for working on this :heart:
