### ISSUE TITLE
Context API

### ISSUE THREAD

**Issue by martinschroeder** [concurrent-php/ext-async#13]
The `Context` API in it's current form is just a container for a task-local map of arbitrary keys (string) to values. As noted by @kelunik using the context like this creates hidden dependencies. This is due to the fact that the context is passed around in an implicit way and provides access to arbitrary values to every execution path.

I do not want to replace the implicit context passing because it allows the `Context` to be passed across borders of APIs that are not aware of context (or async execution) at all. This property is invaluable because it allows for seemless support of context in every location. I do however agree that we need a better way to access contextual data.

Golang has the [context package](https://golang.org/pkg/context/) that IMHO gets cancellation right and i like the immutable context approach a lot. The goal for `Context` should be to support cancellation as a transitive operation using the context API and contextual inheritance. I do not like Go's API as far as acessing contextual variables is concerned because it is like random access to global data all over the place.

Python has introduced [support for context variables](https://www.python.org/dev/peps/pep-0567/) in a different way that is more explicit. They declare individual context variables as objects that need to be passed to consumers in order to access the value for the active context. This approach makes it at least obvious that a contextual variable is used which IMHO is a lot better that just random access to a map of context values. What i don't like about Python's approach is the mutability of the context variables, they can be set and reset at arbitrary times.

My proposal for the Context API is to design it with cancellation and immutability inspired by Go's context API but without support for variables. I want to use a more Python-like approach to context variables albeit without a mutable API.

**Comment by martinschroeder** [comment]
A rough sketch of such an API could look like this:
```php
namespace Concurrent;

final class Context
{
    public function with(ContextVar $var, $value): Context { }
}

final class ContextVar
{
    public function __construct($defaultValue = null, ?string $type = null) { }

    public function get(?Context $context = null) { }
}
```
This would introduce `ContextVar` as the accessor to contextual variables. Since the var object is needed to access the data it would need to be passed to consumers of contextual data making the dependency on a context variable explicit.

**Comment by martinschroeder** [comment]
Now that context variables have been addressed it is time to move on to the cancellation API that should be provided by `Context`. Cancellation has to be enabled by the creator of a `Context` and only the creator of the new context can trigger cancellation. Cancellation is a transitive operation, if a context is cancelled all of it's sub-contexts must be cancelled as well. A `Context` can be shielded from automatic cancellation in exchange for a `CancellationToken` that has to be manually checked to check if cancellation has been requested.

```php
final class Context
{
    ...
    withCancelHandler(): array(Context, CancellationHandler) { }
    withCancellationToken(): array(Context, CancellationToken) { }
    withTimeout(int $milliseconds): Context { }
}

final class CancellationHandler
{
    public function __invoke(?\Throwable $e = null): Awaitable { }
}

final class CancellationToken
{
    public function isCancelled(): void { }
    public function throwIfCancelled(): void { }
}

final class Deferred
{
    public function __construct(callable $cancel = null) { }
    ...
}
```
Cancellation requires to extend `Deferred` with a cancellation mechanism that is exposed to userland. Using a callback is straight forward, the signature of the callback would be `callable(Deferred, ?\Throwable = null)` to allow the cancel handler to resolve or fail the `Deferred` object.

Implementing `Context::withTimeout()` requires an integrated event loop and would allow to specify timeout for every async branch of execution without the need for something like a timeout parameter in all API calls of all components.

**Comment by kelunik** [comment]
@martinschroeder How are double resolutions of `Deferred` objects currently handled? Do they throw an error? e.g. `$deferred->resolve(); $deferred->fail($e);`

**Comment by martinschroeder** [comment]
@kelunik Double resolution is allowed, first one wins.

**Comment by kelunik** [comment]
@martinschroeder While that makes code easier, it might hide bugs. Not sure...
