### ISSUE TITLE
Examining currently running tasks

### ISSUE THREAD

**Issue by kelunik** [concurrent-php/ext-async#34]
It'd be great to have a way to examine at least a count of all currently pending tasks, maybe also the tasks themselves. The use case is to assert that there are no pending tasks in [`LoopReset`](https://github.com/amphp/phpunit-util/blob/82952de84ace0cca62e5db2848eabd8297bb38fa/src/LoopReset.php). `LoopReset` doesn't reset the actual loop anymore but checks for no registered watchers now. A rename of the class to reflect that is pending.

**Comment by martinschroeder** [comment]
The new task scheduler holds a list of suspended (= pending) tasks that could be exposed in PHP. Do you have any suggestions for an API to access that information?

**Comment by kelunik** [comment]
I'd just expose `TaskScheduler::get()` returning the current scheduler and then `getPendingTasks()` or something that returns an array of tasks.

**Comment by martinschroeder** [comment]
I implemented `TaskScheduler::getPendingTasks()` in the scheduler. It will return an array of all suspended tasks. I allso added `getId()`, `getFile()` and `getLine()` to `Task` to allow backtracing a task to the location where it was created.

**Comment by kelunik** [comment]
That's great! I'd keep `getId()` / `getFile()` / `getLine()` instead of forcing the user to use `__debugInfo()`. Providing `__debugInfo()` additionally is fine, but I don't like using ´__debugInfo()` for generating error messages to a user.

**Comment by martinschroeder** [comment]
This has been addressed in #57, information about pending tasks will be provided to the inspection callback passed to `TaskScheduler::run()`.
