### ISSUE TITLE
Undefined property

### ISSUE THREAD

**Issue by kelunik** [concurrent-php/ext-async#35]
For some reason I get the following exception for [this code](https://github.com/amphp/amp/blob/2f7e36aa1afc6e1b0a6070b5ff2a1d6c012ff1e7/lib/Internal/functions.php#L29)

```
Caused by
PHPUnit\Framework\Error\Notice: Undefined property: class@anonymous::$watcher

/home/kelunik/GitHub/amphp/byte-stream/vendor/amphp/amp/lib/Internal/functions.php:29
/home/kelunik/GitHub/amphp/byte-stream/vendor/amphp/amp/lib/Emitter.php:68
/home/kelunik/GitHub/amphp/byte-stream/lib/IteratorStream.php:31
/home/kelunik/GitHub/amphp/byte-stream/test/IteratorStreamTest.php:33
```

Is there anything in `LoopTaskScheduler` that prevents the property from existing or do I simply miss something? [This](https://3v4l.org/oc9An) works fine.

**Comment by martinschroeder** [comment]
I observed the same weird behavior. Does it also happen if you are using a named class instead of an anonymous one?

**Comment by kelunik** [comment]
I'm not sure, because it immediately segfault now when running the tests. The strange thing is, that the `dispatch` property works.

**Comment by martinschroeder** [comment]
I added support for properties to the scheduler classes. It works in a test that uses an anonymous class with properties and a constructor. This should fix the problem.

**Comment by kelunik** [comment]
I think it's fixed, thanks!
