### ISSUE TITLE
References in calls with async keyword

### ISSUE THREAD

**Issue by kelunik** [concurrent-php/ext-async#37]
The `async` keyword allows to automatically turn method calls into a separate fiber / task. How does it handle parameters that are references? Does it preserve the behavior of normal calls there?

**Comment by martinschroeder** [comment]
I checked pass-by-ref and it does not work with async calls at this time. I added checks that throw errors if a function declares by-ref args to `Task::async()` and `Task::asyncWithContext()` to avoid bugs where someone relies on an argument being passed by reference. Returning by reference is ignored for now as it does not cause an error.

I think passing args by ref can only be implemented in PHP core by explicitly creating references for all arguments in the parser. This would be an an internal version of `Task::async()` that accepts all arguments by ref and hands them to to async function as needed.
