### ISSUE TITLE
Add __debugInfo to Deferred

### ISSUE THREAD

**Issue by kelunik** [concurrent-php/ext-async#40]
It should indicate the following information:

```
boolean    pending
mixed      value
\Throwable exception
```

**Comment by martinschroeder** [comment]
I added debug info to `Deferred` and `DeferredAwaitable`. It exposes "status" and "result".

**Comment by kelunik** [comment]
And `result` is either the exception or value then?

**Comment by martinschroeder** [comment]
Yes, `result` contains whatever was used to resolve or fail the `Deferred`. I added to `result` property to `Task` as well to be consistent here.
