### ISSUE TITLE
Task::await on non-Awaitables

### ISSUE THREAD

**Issue by kelunik** [concurrent-php/ext-async#42]
This is a follow-up issue on #41, so we don't forget about the discussed topic. `Task::await` currently simply returns non-Awaitables as given as input. This might hide bugs and should be removed IMO.

I just got `TypeError: All input elements must be awaitable in /home/kelunik/GitHub/amphp/sync/vendor/concurrent-php/async-api/lib/functions.php:47` as an error message which made me aware of a mistake I made. That function could have done the same thing, but I'm glad it didn't, because the resulting code would have done something different than I intended. Same applies to `Task::await`.

**Comment by martinschroeder** [comment]
I just pushed a commit that does change `Task::await()` to require the argument to be an instance of `Awaitable`. I think this is more reliable and consistent than the previous behavior now.
