### ISSUE TITLE
HashTable bailout

### ISSUE THREAD

**Issue by kelunik** [concurrent-php/ext-async#46]
```
PHP Fatal error:  Couldn't execute method Amp\Loop\EventDriver::__destruct in Unknown on line 0
/home/kelunik/.php-build/release/Zend/zend_hash.c(1386) : ht=0x7f9a3207d318 is already destroyed
/home/kelunik/.php-build/release/Zend/zend_hash.c(69) : Bailed out without a bailout address!
```

This happens with `ext-async` enabled and running `composer check` @ https://github.com/amphp/byte-stream/tree/1968a91ef2ac79d892f944e009a50e6a0c353c14

**Comment by martinschroeder** [comment]
Destructors and task / loop scheduling seem to be a risky combination at this point. I don't know if i can do anythingabout that.

I will start working on a builtin event loop next month, this would allow me to provide the scheduler with loop support out of the box and avoid the userland dtor and loop object completely. I sketched quite a few ideas for further APIs and enhancements and will create some more issues to outline the proposed additions and open them up for discussion.

**Comment by martinschroeder** [comment]
I marked this as `wontfix` for now because i want to invest all my spare time into libuv integration. The other thing is that i have absolutely no idea how this could be fixed... 🙄

**Comment by kelunik** [comment]
@martinschroeder This definitely shouldn't be a won't fix. This is more important for a future version of Amp based on `ext-async` than an integrated event loop.

**Comment by martinschroeder** [comment]
I do not really see how this is more important because an integrated libuv would not require any other event loop anyways. I mark this as `help wanted` instead, but i will not be working on this right now.
