### ISSUE TITLE
Stream API

### ISSUE THREAD

**Issue by martinschroeder** [concurrent-php/ext-async#48]
Most projects that provide async IO provide a stream as abstraction of input or putput. I want to provide the contracts for IO streams along with the `async` extension to prevent every project from creating their own (incompatible) interfaces that require adapaters whenever integration with another project is needed.

The interfaces should be closely aligned with `fread()`, `fwrite()` and `fclose()` to provide the very basic building blocks for async IO. My proposed API looks like this:

```php
namespace Concurrent\Stream;

interface ReadableStream
{
    public function close(?\Throwable $e = null): void { }
    public function read(?int $length = null): ?string { }
}

interface WritableStream
{
    public function close(?\Throwable $e = null): void { }
    public function write(string $data): void { }
}

interface DuplexStream extends ReadableStream, WritableStream { }

class StreamException extends \Exception { }
class StreamClosedException extends StreamException { }
```

**Comment by martinschroeder** [comment]
Reading from a stream must stop if `$length` bytes are read or EOF is encountered. If the stream is already at EOF `read()` must return `null`. Reading from a closed (via call to `close()`) stream must throw a `StreamClosedException`. The same error must be thrown when writing to a closed stream.

The `close()` method accepts an additional throwable argument that should be used as previous error whenever a `StreamClosedException` is thrown to provide additional context about the reason for closing the stream.

The more generic `StreamException` should be thrown when an error occurs that is not related to the stream being closed (local or remote), something like an error during encoding or decoding.

If i manage to create a builtin event loop using `libuv` if want to expose the process spawning capabilities of `libuv` to have cross-platform child processes without the need for a custom process wrapper (amphp/process) on Windows. I would use the stream interfaces to model IO pipes to the spawned process.

The `concurrent-php/async-api` package could provide memory-based read / write stream implementations and a few helper functions to work with streams (like `buffer(int $maxSize = null)`).

**Comment by kelunik** [comment]
We (@amphp) have avoided adding a `$length` parameter by-design. The issue is that PHP's current streams always read a certain chunk size and won't trigger any `readable` event if an extension is used instead of `stream_select`. It also makes stream implementations harder to implement. Generally, we haven't felt a `$length` parameter is required for most consumers except for files (I think).

The issue with `amphp/process` isn't launching the process, but the blocking pipes on Windows.

**Comment by martinschroeder** [comment]
I am well aware of the blocking pipe issue on Windows. It has caused me some headache until i started using amp‘s process wrapper which solves the problem at the cost of an additional process, some threads and pipe-to-socket forwarding. Using libuv can further improve this because they are using named pipes instead which saves the overhead of another process an threads.

Adding a length limit to reads IMO does not make it much harder to implement a stream, usually you have some kind of internal buffer anyways. I think the consumer of a stream should be able to limit the amount of data to be consumed. This can for example be useful in protocols with framimg to read only a single packet at a time. The most important aspect is that the buffered data remains with the stream which can be very handy.
