### ISSUE TITLE
Event Loop Integration API

### ISSUE THREAD

**Issue by martinschroeder** [concurrent-php/ext-async#50]
I want to provide an event loop based on `libuv` with the async extension. Using `libuv` provides a rich feature set that covers everything related to non-blocking IO. It is actively maintained and cross-platform with good Windows support.

The first goal is to provide just the basic building blocks and API for async timers and stream read / write watchers. The event loop itself will not be exposed to userland, the task scheduler is responsible for running the loop. As such the default task scheduler wil have event-loop support and no extensions to the scheduler are necessary anymore. I still want to provide some kind of loop scoping to be used in unit tests for proper test isolation (a replacement for the `register()` API).

```php
namespace Concurrent\EventLoop;

final class Timer
{
    public function __construct(callable $callback) { }
    public function close(): void { }
    public function start(): void { }
    public function stop(): void { }
}

final class StreamWatcher
{
    public function __construct(resource $stream) { }
    public function close(?\Throwable $e = null): void { }
    public function awaitReadable(): void { }
    public function awaitWritable(): void { }
}
```
The basic API exposed to userland consists of `Timer` (and maybe `PeriodicTimer`) and `StreamWatcher`. The `Timer` could require a callback to be executed once the timer fires (this would require special handling of errors thrown from within the callback). An alternative solution could be to avoid the callback completely and add a method like `awaitExpired()` that must be called from within a `Task` and will suspend the task until the timer fires (or is stopped).

The `StreamWatcher` watches sockets for readable and writable events. It starts in disabled state and will automatically be enabled when `await*()` is called. Likewise it is disabled automatically after that method returns. There is a dedicated `close()` method that allows to cancel waiting and disable the watcher. The basic workflow in a socket stream would be to attempt a read from the underlying socket, if there is no data available call `awaitReadable()` on the watcher. Read again after the watcher is resumed until you can read some data or encounter an error condition.

**Comment by kelunik** [comment]
If we have a stream abstraction, I'd avoid the stream watchers all together. We still need to figure something for timers.

**Comment by martinschroeder** [comment]
@kelunik We could get rid of the stream watcher for client sockets, but this would require adding another class that can deal with server sockets. Another thing to consider is that establishing a socket connection and enabling TLS encryption also requires a mechanism to be notified when a socket is readable or writable. The proposed `StreamWatcher` is kind of a compromise between a stream API and watcher callbacks. The downside is that it is an additional object instane needed for every socket in addition to a stream.

**Comment by kelunik** [comment]
@martinschroeder Not only an object per socket, but an object per read operation due to the `awaitReadable()`. I think I prefer callbacks over the proposed API.

Why would server sockets need a different API than client sockets?

TLS should be hidden from userland, the current approach is shitty as hell and actually broken in some cases.

**Comment by martinschroeder** [comment]
It is actually one object per stream since `awaitReadable()` does not require an `Awaitable`. It will just suspend the calling task and resume after the event loop indicates the stream is ready. This is a simplified version of what `Task::await()` does.
