### ISSUE TITLE
Clarify whether StreamWatcher can be reused

### ISSUE THREAD

**Issue by kelunik** [concurrent-php/ext-async#61]
The documentation for `Timer` clearly states that they can't be re-used, because a second call shares the same timeout instead of being a new timeout. There's nothing about that in the docs for `StreamWatcher`.

**Comment by martinschroeder** [comment]
I adjusted the readme file to state that both stream and signal watchers can be awaited by multiple tasks and all of them will be continued when the awaited event occurs.
