### ISSUE TITLE
Support for StreamWatcher::reference and StreamWatcher::unreference()

### ISSUE THREAD

**Issue by kelunik** [concurrent-php/ext-async#62]
We need to `unreference()` the watcher for a child's STDERR in `amphp/parallel`, because we want to share the STDERR and pipe it into the parent's STDERR, without keeping the loop alive if that's the only thing going on.

**Comment by martinschroeder** [comment]
This is already supported, the extension supports background contexts. Any task running in a background context will automatically use unreferenced event watchers.

```php
$ctx = Context::current();

Task::asyncWithContext($ctx->background(), function () {
    while (null !== ($chunk = $in->read()) {
}, $in, $out);
```

**Comment by kelunik** [comment]
Can `StreamWatcher` instances be re-used or do I had to create a new `StreamWatcher` per `read()`? Because your approach only works if there's a fresh `StreamWatcher` per `read()`.

**Comment by martinschroeder** [comment]
A `StreamWatcher` can always be reused. It can also be shared by any number of concurrent tasks and supports watching for readability and writability at the same time. The referencing and unreferencing of the watcher is based on the operations queued by the watcher. A watcher will be referenced by default, it will automatically be unreferended if all pending operations are run in background contexts.

> Because your approach only works if there's a fresh StreamWatcher per read().

Care to explain why that should be the case. You can reuse the stream watcher for all `read()` calls just fine.

**Comment by kelunik** [comment]
> Care to explain why that should be the case?

I expected the "unreferenced" state to be checked at construction time. Great work!
