### ISSUE TITLE
Half-open streams

### ISSUE THREAD

**Issue by kelunik** [concurrent-php/ext-async#66]
The current API doesn't allow for half-open streams, because `DuplexStream::close()` will close both sides.

**Comment by martinschroeder** [comment]
Calling `close()` will indeed close the stream completely. `DuplexStream` could be extended with `closeRead()` and `closeWrite()` to provide a way to close just the read or write side.

**Comment by kelunik** [comment]
It needs another wrapper then to pass a `DuplexStream` to a function that calls `close()`, so maybe rather `DuplexStream->getReadableStream()` and `DuplexStream->getWritableStream()`?

**Comment by martinschroeder** [comment]
This has been implemented, methods are named `readStream()` and `writeStream()`.
