### ISSUE TITLE
Throwing an exception on global right after Task::async()

### ISSUE THREAD

**Issue by sj-i** [concurrent-php/ext-async#75]
Throwing an exception on global right after Task::async() couldn't be catched by the global exception handler.

```
<?php
use Concurrent\Task;

Task::async(function () {});
set_exception_handler(function($e){var_dump($e);});
throw new \Exception;
```

expected:
outputs the contents of the exception

actual:
outputs nothing

**Comment by martinschroeder** [comment]
I fixed this bug by backing up and restoring the error thrown from global context before running async tasks. Note that all async tasks still run to completion at the end of main. If you `var_dump()` in your task it will be executed before the exception handler.
