### ISSUE TITLE
'None of the awaitables resolved' triggered when it shouldn't

### ISSUE THREAD

**Issue by kelunik** [concurrent-php/ext-async#76]
Executing [these tests](https://github.com/amphp/amp/blob/2917687e7274cfe4f83597912d0abc0fa7d7b196/test/TimeoutTest.php#L32-L68) shouldn't result in failures, but results in:

```
1) Amp\Test\TimeoutTest::testFailure
Failed asserting that exception message is empty but is 'None of the awaitables resolved'.

/home/kelunik/GitHub/amphp/amp/vendor/concurrent-php/async-api/src/AsyncTestCase.php:36

2) Amp\Test\TimeoutTest::testSlowPending
Failed asserting that exception of type "Amp\TimeoutException" is thrown.

/home/kelunik/GitHub/amphp/amp/vendor/concurrent-php/async-api/src/AsyncTestCase.php:36
```

**Comment by martinschroeder** [comment]
This was caused by `race()` not behaving the way you thought it would. I aligned the behavior of `race()` with JavaScript's `Promise.race()` to avoid confusion, your tests work just fine with my latest commit.
