### ISSUE TITLE
HTTP support

### ISSUE THREAD

**Issue by torinaki** [concurrent-php/ext-async#96]
I'm not sure is this relevant or not. Is there plan to add HTTP protocol support? 
Let say implementation can be based using existing HTTP libraries like [nghttp2/nghttp2](https://github.com/nghttp2/nghttp2) (HTTP/2) and [h2o/picohttpparser](https://github.com/h2o/picohttpparser) (HTTP/1).

**Comment by kelunik** [comment]
I'm currently at porting [Artax](https://github.com/amphp/artax) to `ext-async`.

**Comment by torinaki** [comment]
Probably I should be more specific. My question is more related to TCP server which can parse HTTP requests bodies of incoming connections.

**Comment by kelunik** [comment]
Ah, I'll also work on porting http-server to ext-async. Not sure how much should be directly in the extension.

**Comment by kelunik** [comment]
@torinaki I'm also for an HTTP parser in an extension, but it doesn't have to be in `ext-async`, in could be a generic `http-parser` extension that can also be used without `ext-async`.

**Comment by torinaki** [comment]
@martinschroeder, @kelunik thanks you for the explanation. I'm closing this ticket.
